# Identificadores de tu proyecto
sonar.organization=trickershile
sonar.projectKey=trickershile_evaluacionN2Devops

# Configuración de Python corregida para hacer match con el pipeline
sonar.python.version=3.11
sonar.sources=.
sonar.exclusions=test_app.py, **/__pycache__/**, .github/**

# Configuración de las Pruebas
sonar.tests=.
sonar.test.inclusions=test_app.py