# Identificadores de tu proyecto (Cámbialos por los tuyos)
sonar.organization=trickershile
sonar.projectKey=trickershile_evaluacionN2Devops

# Configuración de Python
sonar.python.version=3.9
sonar.sources=.
sonar.exclusions=test_app.py, **/__pycache__/**, .github/**

# Configuración de las Pruebas
sonar.tests=.
sonar.test.inclusions=test_app.py